### ISSUE TITLE
RTD build has been failing for a while

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1098]
The following command is causing a timeout because it's attempting to connect to mongo at localhost:27017.

    python /home/docs/checkouts/readthedocs.org/user_builds/girder/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html

The error output:

```
/home/docs/checkouts/readthedocs.org/user_builds/girder/checkouts/latest/docs/api-docs.rst:149: WARNING: autodoc: failed to import module u'girder.api.api_main'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/checkouts/latest/girder/api/api_main.py", line 23, in <module>
    from .v1 import assetstore, file, collection, folder, group, item, resource,\
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/checkouts/latest/girder/api/v1/file.py", line 31, in <module>
    class File(Resource):
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/checkouts/latest/girder/api/v1/file.py", line 211, in File
    @loadmodel(model='file', level=AccessType.READ)
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/checkouts/latest/girder/api/rest.py", line 233, in __init__
    self.model = ModelImporter.model(model, plugin)
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/checkouts/latest/girder/utility/model_importer.py", line 93, in model
    _loadModel(model, module, plugin)
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/checkouts/latest/girder/utility/model_importer.py", line 47, in _loadModel
    _modelInstances[plugin][model] = constructor()
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/checkouts/latest/girder/models/model_base.py", line 61, in __init__
    self.reconnect()
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/checkouts/latest/girder/models/model_base.py", line 76, in reconnect
    self.collection.create_index(index)
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/checkouts/latest/girder/external/mongodb_proxy.py", line 83, in __call__
    return self.method(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/envs/latest/local/lib/python2.7/site-packages/pymongo/collection.py", line 1163, in create_index
    self.__create_index(keys, kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/envs/latest/local/lib/python2.7/site-packages/pymongo/collection.py", line 1074, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/envs/latest/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 663, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/envs/latest/local/lib/python2.7/site-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/home/docs/checkouts/readthedocs.org/user_builds/girder/envs/latest/local/lib/python2.7/site-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```

**Comment by jbeezley** [comment]
RTD imports all of the files that it runs autodoc on, and often you need to mock certain pieces or imports to get it to work.  This can be done in the sphinx conf.py.  In this case, it might be debatable if just importing a model should cause it to hit the database.  Should the connection be established lazily instead?

**Comment by zachmullen** [comment]
@jbeezley #1099

**Comment by zachmullen** [comment]
> In this case, it might be debatable if just importing a model should cause it to hit the database. Should the connection be established lazily instead?

Importing a module (in the sense of a python `import`) should not and does not cause it to connect to the database. However, using `ModelImporter.model(...)` does cause it to connect to the database, because it's actually calling the model class constructor, which I think is OK behavior for now.

As a rule, we will just have to make sure we don't actually construct any models in code that executes during a python module import. The culprit in this case was `girder.api.rest.loadmodel.__init__`, which was easy to miss since it looks like a decorator in the code but in fact is a constructor call that returns a decorator callable.
