### ISSUE TITLE
Travis failure: web_client_folder

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1303]
The `web_client_folder` test is occasionally failing on Travis with the following log output:
```
      Start  64: web_client_folder
64: Test command: /home/travis/virtualenv/python3.4.2/bin/python3.4 "-m" "unittest" "-v" "tests.web_client_test"
64: Environment variables: 
64:  PYTHONPATH=
64:  SPEC_FILE=/home/travis/build/girder/girder/clients/web/test/spec/folderSpec.js
64:  ASSETSTORE_TYPE=filesystem
64:  WEB_SECURITY=true
64:  ENABLED_PLUGINS=
64:  PLUGIN_DIRS=
64:  GIRDER_TEST_DB=mongodb://localhost:27017/girder_test_web_client_folder
64:  GIRDER_TEST_ASSETSTORE=web_client_folder
64:  GIRDER_PORT=30010
64:  COVERAGE_FILE=/home/travis/build/girder/girder/_build/js_coverage/folder.cvg
64: Test timeout computed to be: 600
64: [08/Apr/2016:15:26:51] ENGINE Bus STARTING
64: [08/Apr/2016:15:26:51] ENGINE Started monitor thread '_TimeoutMonitor'.
64: [08/Apr/2016:15:26:51] ENGINE Serving on http://0.0.0.0:30010
64: [08/Apr/2016:15:26:51] ENGINE Bus STARTED
64: testWebClientSpec (tests.web_client_test.WebClientTestCase) ... [1;33mMocking Girder log methods.[0m
64: [35mRunning in mode: testing[0m
64: [35mResolving plugin dependencies...[0m
64: [35mStarted asynchronous event manager thread.[0m
64: [35mConnected to MongoDB: mongodb://localhost:27017/girder_test_web_client_folder[0m
64: -----------------------
64: Jasmine runner starting
64: -----------------------
64: [32m. Test folder creation, editing, and deletion -> register a user[0m
64: [32m. Test folder creation, editing, and deletion -> go to users page[0m
64: [32m. Test folder creation, editing, and deletion -> view the users on the user page and click on one[0m
64: 401 Unauthorized {"message": "Read access denied for folder 5707cdbf552d0c12369ad634 (user None).", "type": "access"}
64: [31mF Test folder creation, editing, and deletion -> test that anonymous loading the private folder of the user prompts a login dialog[0m
64: Created screenshot: phantom-2016-04-08T15.27.11.166Z.png
64: <DartMeasurementFile name="PhantomScreenshot" type="image/png">/home/travis/build/girder/girder/phantom-2016-04-08T15.27.11.166Z.png</DartMeasurementFile>
64: Dumping ajax trace:
64: [
64:   {
64:     "opts": {
64:       "dataType": "json",
64:       "type": "GET",
64:       "method": "GET",
64:       "path": "/user/me",
64:       "url": "http://localhost:30010//api/v1/user/me"
64:     },
64:     "status": "success",
64:     "result": null
64:   },
64:   {
64:     "opts": {
64:       "dataType": "json",
64:       "type": "POST",
64:       "error": null,
64:       "path": "/user",
64:       "data": {
64:         "login": "admin",
64:         "password": "adminpassword!",
64:         "email": "admin@email.com",
64:         "firstName": "Admin",
64:         "lastName": "Admin"
64:       },
64:       "url": "http://localhost:30010//api/v1/user"
64:     },
64:     "status": "success",
64:     "result": {
64:       "_accessLevel": 2,
64:       "_id": "5707cdbf552d0c12369ad632",
64:       "_modelType": "user",
64:       "admin": true,
64:       "authToken": {
64:         "expires": "2016-10-05T15:26:55.740991+00:00",
64:         "token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
64:       },
64:       "created": "2016-04-08T15:26:55.464501+00:00",
64:       "email": "admin@email.com",
64:       "firstName": "Admin",
64:       "groupInvites": [],
64:       "groups": [],
64:       "lastName": "Admin",
64:       "login": "admin",
64:       "public": true,
64:       "size": 0
64:     }
64:   },
64:   {
64:     "opts": {
64:       "dataType": "json",
64:       "type": "GET",
64:       "path": "/user",
64:       "data": {
64:         "limit": 26,
64:         "offset": 0,
64:         "sort": "lastName",
64:         "sortdir": 1
64:       },
64:       "url": "http://localhost:30010//api/v1/user",
64:       "headers": {
64:         "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
64:       }
64:     },
64:     "status": "success",
64:     "result": [
64:       {
64:         "_accessLevel": 2,
64:         "_id": "5707cdbf552d0c12369ad632",
64:         "_modelType": "user",
64:         "admin": true,
64:         "created": "2016-04-08T15:26:55.464000+00:00",
64:         "email": "admin@email.com",
64:         "firstName": "Admin",
64:         "groupInvites": [],
64:         "groups": [],
64:         "lastName": "Admin",
64:         "login": "admin",
64:         "public": true,
64:         "size": 0
64:       }
64:     ]
64:   },
64:   {
64:     "opts": {
64:       "dataType": "json",
64:       "type": "GET",
64:       "path": "/user/5707cdbf552d0c12369ad632",
64:       "url": "http://localhost:30010//api/v1/user/5707cdbf552d0c12369ad632",
64:       "headers": {
64:         "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
64:       }
64:     },
64:     "status": "success",
64:     "result": {
64:       "_accessLevel": 2,
64:       "_id": "5707cdbf552d0c12369ad632",
64:       "_modelType": "user",
64:       "admin": true,
64:       "created": "2016-04-08T15:26:55.464000+00:00",
64:       "email": "admin@email.com",
64:       "firstName": "Admin",
64:       "groupInvites": [],
64:       "groups": [],
64:       "lastName": "Admin",
64:       "login": "admin",
64:       "public": true,
64:       "size": 0
64:     }
64:   },
64:   {
64:     "opts": {
64:       "dataType": "json",
64:       "type": "GET",
64:       "path": "/folder",
64:       "data": {
64:         "limit": 101,
64:         "offset": 0,
64:         "sort": "name",
64:         "sortdir": 1,
64:         "parentType": "user",
64:         "parentId": "5707cdbf552d0c12369ad632"
64:       },
64:       "url": "http://localhost:30010//api/v1/folder",
64:       "headers": {
64:         "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
64:       }
64:     },
64:     "status": "success",
64:     "result": [
64:       {
64:         "_accessLevel": 2,
64:         "_id": "5707cdbf552d0c12369ad634",
64:         "_modelType": "folder",
64:         "baseParentId": "5707cdbf552d0c12369ad632",
64:         "baseParentType": "user",
64:         "created": "2016-04-08T15:26:55.737000+00:00",
64:         "creatorId": "5707cdbf552d0c12369ad632",
64:         "description": "",
64:         "name": "Private",
64:         "parentCollection": "user",
64:         "parentId": "5707cdbf552d0c12369ad632",
64:         "public": false,
64:         "size": 0,
64:         "updated": "2016-04-08T15:26:55.737000+00:00"
64:       },
64:       {
64:         "_accessLevel": 2,
64:         "_id": "5707cdbf552d0c12369ad633",
64:         "_modelType": "folder",
64:         "baseParentId": "5707cdbf552d0c12369ad632",
64:         "baseParentType": "user",
64:         "created": "2016-04-08T15:26:55.736000+00:00",
64:         "creatorId": "5707cdbf552d0c12369ad632",
64:         "description": "",
64:         "name": "Public",
64:         "parentCollection": "user",
64:         "parentId": "5707cdbf552d0c12369ad632",
64:         "public": true,
64:         "size": 0,
64:         "updated": "2016-04-08T15:26:55.736000+00:00"
64:       }
64:     ]
64:   },
64:   {
64:     "opts": {
64:       "dataType": "json",
64:       "type": "GET",
64:       "path": "/folder",
64:       "data": {
64:         "limit": 101,
64:         "offset": 0,
64:         "sort": "name",
64:         "sortdir": 1,
64:         "parentType": "folder",
64:         "parentId": "5707cdbf552d0c12369ad634"
64:       },
64:       "url": "http://localhost:30010//api/v1/folder",
64:       "headers": {
64:         "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
64:       }
64:     },
64:     "status": "success",
64:     "result": []
64:   },
64:   {
64:     "opts": {
64:       "dataType": "json",
64:       "type": "GET",
64:       "path": "/item",
64:       "data": {
64:         "limit": 101,
64:         "offset": 0,
64:         "sort": "name",
64:         "sortdir": 1,
64:         "folderId": "5707cdbf552d0c12369ad634"
64:       },
64:       "url": "http://localhost:30010//api/v1/item",
64:       "headers": {
64:         "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
64:       }
64:     },
64:     "status": "success",
64:     "result": []
64:   },
64:   {
64:     "opts": {
64:       "dataType": "json",
64:       "type": "GET",
64:       "path": "/folder/5707cdbf552d0c12369ad634/details",
64:       "url": "http://localhost:30010//api/v1/folder/5707cdbf552d0c12369ad634/details",
64:       "headers": {
64:         "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
64:       }
64:     },
64:     "status": "error",
64:     "errorThrown": "Unauthorized"
64:   },
64:   {
64:     "opts": {
64:       "dataType": "json",
64:       "type": "GET",
64:       "method": "DELETE",
64:       "path": "/user/authentication",
64:       "url": "http://localhost:30010//api/v1/user/authentication",
64:       "headers": {
64:         "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
64:       }
64:     },
64:     "status": "success",
64:     "result": {
64:       "message": "Logged out."
64:     }
64:   }
64: ]
64: [31m
64:  Error: timeout: timed out after 15000 msec waiting for any modal dialog to be hidden[0m
64: [31mF Test folder creation, editing, and deletion -> create a subfolder in the public folder of the user[0m
64: Created screenshot: phantom-2016-04-08T15.27.26.601Z.png
64: <DartMeasurementFile name="PhantomScreenshot" type="image/png">/home/travis/build/girder/girder/phantom-2016-04-08T15.27.26.601Z.png</DartMeasurementFile>
64: Dumping ajax trace:
64: []
64: [31m
64:  Error: timeout: timed out after 15000 msec waiting for the public folder to be clickable[0m
64: [31mF Test folder creation, editing, and deletion -> Open edit dialog and check url state[0m
64: Created screenshot: phantom-2016-04-08T15.27.42.047Z.png
64: <DartMeasurementFile name="PhantomScreenshot" type="image/png">/home/travis/build/girder/girder/phantom-2016-04-08T15.27.42.047Z.png</DartMeasurementFile>
64: Dumping ajax trace:
64: []
64: [31m
64:  Error: timeout: timed out after 15000 msec waiting for the folder actions button to appear[0m
64: [31mF Test folder creation, editing, and deletion -> Add, edit, and delete metadata for the folder[0m
64: Created screenshot: phantom-2016-04-08T15.27.57.491Z.png
64: <DartMeasurementFile name="PhantomScreenshot" type="image/png">/home/travis/build/girder/girder/phantom-2016-04-08T15.27.57.491Z.png</DartMeasurementFile>
64: Dumping ajax trace:
64: []
64: [31m
64:  Error: timeout: timed out after 15000 msec waiting for the add metadata button to appear[0m
64: [31mF Test folder creation, editing, and deletion -> Open edit dialog and save the folder[0m
64: Created screenshot: phantom-2016-04-08T15.28.13.014Z.png
64: <DartMeasurementFile name="PhantomScreenshot" type="image/png">/home/travis/build/girder/girder/phantom-2016-04-08T15.28.13.014Z.png</DartMeasurementFile>
64: Dumping ajax trace:
64: []
64: [31m
64:  Error: timeout: timed out after 15000 msec waiting for the folder actions button to appear[0m
64: [31mF Test folder creation, editing, and deletion -> Test folder view and navigation[0m
64: Created screenshot: phantom-2016-04-08T15.28.28.391Z.png
64: <DartMeasurementFile name="PhantomScreenshot" type="image/png">/home/travis/build/girder/girder/phantom-2016-04-08T15.28.28.391Z.png</DartMeasurementFile>
64: Dumping ajax trace:
64: []
64: [31m
64:  Error: timeout: timed out after 15000 msec waiting for folder actions to be available[0m
64: [31mF Test folder creation, editing, and deletion -> Test folder access control[0m
64: Created screenshot: phantom-2016-04-08T15.28.43.747Z.png
64: <DartMeasurementFile name="PhantomScreenshot" type="image/png">/home/travis/build/girder/girder/phantom-2016-04-08T15.28.43.747Z.png</DartMeasurementFile>
64: Dumping ajax trace:
64: []
64: [31m
64:  Error: timeout: timed out after 15000 msec waiting for folder access button to be available[0m
64: [31mF Test folder creation, editing, and deletion -> Delete the folder[0m
64: Created screenshot: phantom-2016-04-08T15.28.59.109Z.png
64: <DartMeasurementFile name="PhantomScreenshot" type="image/png">/home/travis/build/girder/girder/phantom-2016-04-08T15.28.59.109Z.png</DartMeasurementFile>
64: Dumping ajax trace:
64: []
64: [31m
64:  Error: timeout: timed out after 15000 msec waiting for the folder actions button to appear[0m
64: 
64: [31mTest folder creation, editing, and deletion: 7 of 15 passed.[0m
64: ----------------
64: Testing Finished
64: ----------------
64: [31m11 specs, 8 failures in 124.077s.[0m
64: 
64: ConsoleReporter finished
64: Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///home/travis/build/girder/girder/clients/web/test/specRunner.js. Domains, protocols and ports must match.
64: 
64: Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///home/travis/build/girder/girder/clients/web/test/specRunner.js. Domains, protocols and ports must match.
64: 
64: FAIL
64: /opt/python/3.4.2/lib/python3.4/unittest/case.py:605: ResourceWarning: unclosed file <_io.BufferedReader name=11>
64:   outcome.errors.clear()
64: /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py:1666: ResourceWarning: unclosed <socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 30010), raddr=('127.0.0.1', 53504)>
64:   self.tick()
64: 
64: ======================================================================
64: FAIL: testWebClientSpec (tests.web_client_test.WebClientTestCase)
64: ----------------------------------------------------------------------
64: Traceback (most recent call last):
64:   File "/home/travis/build/girder/girder/tests/web_client_test.py", line 198, in testWebClientSpec
64:     self.assertEqual(returncode, 0)
64: AssertionError: 1 != 0
64: 
64: ----------------------------------------------------------------------
64: Ran 1 test in 128.313s
64: 
64: FAILED (failures=1)
34/36 Test  #64: web_client_folder ..................***Failed  129.05 sec
```

**Comment by zachmullen** [comment]
```
[08/Apr/2016:15:26:51] ENGINE Bus STARTING
[08/Apr/2016:15:26:51] ENGINE Started monitor thread '_TimeoutMonitor'.
[08/Apr/2016:15:26:51] ENGINE Serving on http://0.0.0.0:30010
[08/Apr/2016:15:26:51] ENGINE Bus STARTED
testWebClientSpec (tests.web_client_test.WebClientTestCase) ... [NON-XML-CHAR-0x1B][1;33mMocking Girder log methods.[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][35mRunning in mode: testing[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][35mResolving plugin dependencies...[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][35mStarted asynchronous event manager thread.[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][35mConnected to MongoDB: mongodb://localhost:27017/girder_test_web_client_folder[NON-XML-CHAR-0x1B][0m
-----------------------
Jasmine runner starting
-----------------------
[NON-XML-CHAR-0x1B][32m. Test folder creation, editing, and deletion -> register a user[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][32m. Test folder creation, editing, and deletion -> go to users page[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][32m. Test folder creation, editing, and deletion -> view the users on the user page and click on one[NON-XML-CHAR-0x1B][0m
401 Unauthorized {"message": "Read access denied for folder 5707cdbf552d0c12369ad634 (user None).", "type": "access"}
[NON-XML-CHAR-0x1B][31mF Test folder creation, editing, and deletion -> test that anonymous loading the private folder of the user prompts a login dialog[NON-XML-CHAR-0x1B][0m
Created screenshot: phantom-2016-04-08T15.27.11.166Z.png

Dumping ajax trace:
[
  {
    "opts": {
      "dataType": "json",
      "type": "GET",
      "method": "GET",
      "path": "/user/me",
      "url": "http://localhost:30010//api/v1/user/me"
    },
    "status": "success",
    "result": null
  },
  {
    "opts": {
      "dataType": "json",
      "type": "POST",
      "error": null,
      "path": "/user",
      "data": {
        "login": "admin",
        "password": "adminpassword!",
        "email": "admin@email.com",
        "firstName": "Admin",
        "lastName": "Admin"
      },
      "url": "http://localhost:30010//api/v1/user"
    },
    "status": "success",
    "result": {
      "_accessLevel": 2,
      "_id": "5707cdbf552d0c12369ad632",
      "_modelType": "user",
      "admin": true,
      "authToken": {
        "expires": "2016-10-05T15:26:55.740991+00:00",
        "token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
      },
      "created": "2016-04-08T15:26:55.464501+00:00",
      "email": "admin@email.com",
      "firstName": "Admin",
      "groupInvites": [],
      "groups": [],
      "lastName": "Admin",
      "login": "admin",
      "public": true,
      "size": 0
    }
  },
  {
    "opts": {
      "dataType": "json",
      "type": "GET",
      "path": "/user",
      "data": {
        "limit": 26,
        "offset": 0,
        "sort": "lastName",
        "sortdir": 1
      },
      "url": "http://localhost:30010//api/v1/user",
      "headers": {
        "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
      }
    },
    "status": "success",
    "result": [
      {
        "_accessLevel": 2,
        "_id": "5707cdbf552d0c12369ad632",
        "_modelType": "user",
        "admin": true,
        "created": "2016-04-08T15:26:55.464000+00:00",
        "email": "admin@email.com",
        "firstName": "Admin",
        "groupInvites": [],
        "groups": [],
        "lastName": "Admin",
        "login": "admin",
        "public": true,
        "size": 0
      }
    ]
  },
  {
    "opts": {
      "dataType": "json",
      "type": "GET",
      "path": "/user/5707cdbf552d0c12369ad632",
      "url": "http://localhost:30010//api/v1/user/5707cdbf552d0c12369ad632",
      "headers": {
        "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
      }
    },
    "status": "success",
    "result": {
      "_accessLevel": 2,
      "_id": "5707cdbf552d0c12369ad632",
      "_modelType": "user",
      "admin": true,
      "created": "2016-04-08T15:26:55.464000+00:00",
      "email": "admin@email.com",
      "firstName": "Admin",
      "groupInvites": [],
      "groups": [],
      "lastName": "Admin",
      "login": "admin",
      "public": true,
      "size": 0
    }
  },
  {
    "opts": {
      "dataType": "json",
      "type": "GET",
      "path": "/folder",
      "data": {
        "limit": 101,
        "offset": 0,
        "sort": "name",
        "sortdir": 1,
        "parentType": "user",
        "parentId": "5707cdbf552d0c12369ad632"
      },
      "url": "http://localhost:30010//api/v1/folder",
      "headers": {
        "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
      }
    },
    "status": "success",
    "result": [
      {
        "_accessLevel": 2,
        "_id": "5707cdbf552d0c12369ad634",
        "_modelType": "folder",
        "baseParentId": "5707cdbf552d0c12369ad632",
        "baseParentType": "user",
        "created": "2016-04-08T15:26:55.737000+00:00",
        "creatorId": "5707cdbf552d0c12369ad632",
        "description": "",
        "name": "Private",
        "parentCollection": "user",
        "parentId": "5707cdbf552d0c12369ad632",
        "public": false,
        "size": 0,
        "updated": "2016-04-08T15:26:55.737000+00:00"
      },
      {
        "_accessLevel": 2,
        "_id": "5707cdbf552d0c12369ad633",
        "_modelType": "folder",
        "baseParentId": "5707cdbf552d0c12369ad632",
        "baseParentType": "user",
        "created": "2016-04-08T15:26:55.736000+00:00",
        "creatorId": "5707cdbf552d0c12369ad632",
        "description": "",
        "name": "Public",
        "parentCollection": "user",
        "parentId": "5707cdbf552d0c12369ad632",
        "public": true,
        "size": 0,
        "updated": "2016-04-08T15:26:55.736000+00:00"
      }
    ]
  },
  {
    "opts": {
      "dataType": "json",
      "type": "GET",
      "path": "/folder",
      "data": {
        "limit": 101,
        "offset": 0,
        "sort": "name",
        "sortdir": 1,
        "parentType": "folder",
        "parentId": "5707cdbf552d0c12369ad634"
      },
      "url": "http://localhost:30010//api/v1/folder",
      "headers": {
        "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
      }
    },
    "status": "success",
    "result": []
  },
  {
    "opts": {
      "dataType": "json",
      "type": "GET",
      "path": "/item",
      "data": {
        "limit": 101,
        "offset": 0,
        "sort": "name",
        "sortdir": 1,
        "folderId": "5707cdbf552d0c12369ad634"
      },
      "url": "http://localhost:30010//api/v1/item",
      "headers": {
        "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
      }
    },
    "status": "success",
    "result": []
  },
  {
    "opts": {
      "dataType": "json",
      "type": "GET",
      "path": "/folder/5707cdbf552d0c12369ad634/details",
      "url": "http://localhost:30010//api/v1/folder/5707cdbf552d0c12369ad634/details",
      "headers": {
        "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
      }
    },
    "status": "error",
    "errorThrown": "Unauthorized"
  },
  {
    "opts": {
      "dataType": "json",
      "type": "GET",
      "method": "DELETE",
      "path": "/user/authentication",
      "url": "http://localhost:30010//api/v1/user/authentication",
      "headers": {
        "Girder-Token": "D2nuDIR1Bk5oHDOUK4dmC9VWcNKHLy1rKtExJ0onu8MKcWmyBxbwIuFNj0kpBQB6"
      }
    },
    "status": "success",
    "result": {
      "message": "Logged out."
    }
  }
]
[NON-XML-CHAR-0x1B][31m
 Error: timeout: timed out after 15000 msec waiting for any modal dialog to be hidden[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][31mF Test folder creation, editing, and deletion -> create a subfolder in the public folder of the user[NON-XML-CHAR-0x1B][0m
Created screenshot: phantom-2016-04-08T15.27.26.601Z.png

Dumping ajax trace:
[]
[NON-XML-CHAR-0x1B][31m
 Error: timeout: timed out after 15000 msec waiting for the public folder to be clickable[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][31mF Test folder creation, editing, and deletion -> Open edit dialog and check url state[NON-XML-CHAR-0x1B][0m
Created screenshot: phantom-2016-04-08T15.27.42.047Z.png

Dumping ajax trace:
[]
[NON-XML-CHAR-0x1B][31m
 Error: timeout: timed out after 15000 msec waiting for the folder actions button to appear[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][31mF Test folder creation, editing, and deletion -> Add, edit, and delete metadata for the folder[NON-XML-CHAR-0x1B][0m
Created screenshot: phantom-2016-04-08T15.27.57.491Z.png

Dumping ajax trace:
[]
[NON-XML-CHAR-0x1B][31m
 Error: timeout: timed out after 15000 msec waiting for the add metadata button to appear[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][31mF Test folder creation, editing, and deletion -> Open edit dialog and save the folder[NON-XML-CHAR-0x1B][0m
Created screenshot: phantom-2016-04-08T15.28.13.014Z.png

Dumping ajax trace:
[]
[NON-XML-CHAR-0x1B][31m
 Error: timeout: timed out after 15000 msec waiting for the folder actions button to appear[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][31mF Test folder creation, editing, and deletion -> Test folder view and navigation[NON-XML-CHAR-0x1B][0m
Created screenshot: phantom-2016-04-08T15.28.28.391Z.png

Dumping ajax trace:
[]
[NON-XML-CHAR-0x1B][31m
 Error: timeout: timed out after 15000 msec waiting for folder actions to be available[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][31mF Test folder creation, editing, and deletion -> Test folder access control[NON-XML-CHAR-0x1B][0m
Created screenshot: phantom-2016-04-08T15.28.43.747Z.png

Dumping ajax trace:
[]
[NON-XML-CHAR-0x1B][31m
 Error: timeout: timed out after 15000 msec waiting for folder access button to be available[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][31mF Test folder creation, editing, and deletion -> Delete the folder[NON-XML-CHAR-0x1B][0m
Created screenshot: phantom-2016-04-08T15.28.59.109Z.png

Dumping ajax trace:
[]
[NON-XML-CHAR-0x1B][31m
 Error: timeout: timed out after 15000 msec waiting for the folder actions button to appear[NON-XML-CHAR-0x1B][0m

[NON-XML-CHAR-0x1B][31mTest folder creation, editing, and deletion: 7 of 15 passed.[NON-XML-CHAR-0x1B][0m
----------------
Testing Finished
----------------
[NON-XML-CHAR-0x1B][31m11 specs, 8 failures in 124.077s.[NON-XML-CHAR-0x1B][0m

ConsoleReporter finished
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///home/travis/build/girder/girder/clients/web/test/specRunner.js. Domains, protocols and ports must match.

Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///home/travis/build/girder/girder/clients/web/test/specRunner.js. Domains, protocols and ports must match.

FAIL
/opt/python/3.4.2/lib/python3.4/unittest/case.py:605: ResourceWarning: unclosed file <_io.BufferedReader name=11>
  outcome.errors.clear()
/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py:1666: ResourceWarning: unclosed <socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 30010), raddr=('127.0.0.1', 53504)>
  self.tick()

======================================================================
FAIL: testWebClientSpec (tests.web_client_test.WebClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/girder/girder/tests/web_client_test.py", line 198, in testWebClientSpec
    self.assertEqual(returncode, 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 1 test in 128.313s

FAILED (failures=1)

```

(Pasted here since these records eventually get deleted from CDash).

**Comment by zachmullen** [comment]
The screenshots from the failures are all this:

![displayimage](https://cloud.githubusercontent.com/assets/555959/14389541/16236b0e-fd81-11e5-9a93-0930c4e33203.png)

**Comment by brianhelba** [comment]
@zachmullen I deleted your comment with the redundant log output. My finger got a little heavy when I was making this issue, and I created it prematurely.

**Comment by zachmullen** [comment]
I believe this has now been fixed, this was a race condition occurring across a few different tests.
