### ISSUE TITLE
Log in to hub.yt through Github fails

### ISSUE THREAD

**Issue by CamiloHPenaloza** [girder/girder#1509]
When trying to log into hub.yt using my github account I get the following message:

{
    "message": "Invalid CSRF token (state=\"z7XYtLC6b63gUAThc0FcaEniJzqxagxsxA56BSPi9dLdqRIQmnCLKooft0fZc1tj.https://girder.hub.yt/#\").",
    "type": "rest"
}

{
    "message": "AttributeError: AttributeError(\"'NoneType' object has no attribute 'split'\",)",
    "type": "internal"
}

How can I fix this or is this some bug?

Thanks,

**Comment by zachmullen** [comment]
On latest master on my local machine, I am able to login with github as both a new and existing user. I am not an administrator of hub.yt, though I believe @Xarthisius has the ability to see the full logs there.

**Comment by zachmullen** [comment]
When I try to log in to hub.yt, I get the `KeyError: KeyError('status',)`, which is an issue that has been resolved on latest master. If that's the underlying cause, an upgrade of the server should fix your issue.

**Comment by Xarthisius** [comment]
There were 2 separate tracebacks:

```
Traceback (most recent call last):
  File "/girder/girder/api/rest.py", line 489, in endpointDecorator
    val = fun(self, args, kwargs)
  File "/girder/girder/api/rest.py", line 1024, in GET
    return self.handleRoute('GET', path, params)
  File "/girder/girder/api/rest.py", line 812, in handleRoute
    val = handler(**kwargs)
  File "/girder/plugins/oauth/server/rest.py", line 132, in callback
    user = providerObj.getUser(token)
  File "/girder/plugins/oauth/server/providers/github.py", line 114, in getUser
    login)
  File "/girder/plugins/oauth/server/providers/base.py", line 184, in _createOrReuseUser
    user = cls.model('user').save(user)
  File "/girder/girder/models/model_base.py", line 345, in save
    document = self.validate(document)
  File "/girder/girder/models/user.py", line 97, in validate
    if doc['status'] not in ('pending', 'enabled', 'disabled'):
KeyError: 'status'
```

and

```
Traceback (most recent call last):
  File "/girder/girder/api/rest.py", line 489, in endpointDecorator
    val = fun(self, args, kwargs)
  File "/girder/girder/api/rest.py", line 1024, in GET
    return self.handleRoute('GET', path, params)
  File "/girder/girder/api/rest.py", line 812, in handleRoute
    val = handler(**kwargs)
  File "/girder/plugins/oauth/server/rest.py", line 132, in callback
    user = providerObj.getUser(token)
  File "/girder/plugins/oauth/server/providers/github.py", line 109, in getUser
    names = resp.get('name', '').split()
AttributeError: 'NoneType' object has no attribute 'split'
```

I've fixed the former by applying PR 1497. I can log in now. Not sure what triggers the 2nd one.

**Comment by Xarthisius** [comment]
I guess that's the issue:

```
$ curl -i https://api.github.com/users/CamiloHPenaloza

{
  "login": "CamiloHPenaloza",
  ...
  "name": null,
}
```

**Comment by zachmullen** [comment]
I see the issue, it appears people who have not listed their real name in github have the value returned as `null` in JSON, so this is an actual bug. We'll have to invent some value for their name in this case since girder requires it.

In the mean time, @CamiloHPenaloza if you want to work around this, add your name to your github account and the login should work.

**Comment by CamiloHPenaloza** [comment]
That makes perfect sense since I just recently created my github account and haven't gotten around to doing much with it. Thanks for the help!
