### ISSUE TITLE
cherrypy is not in requirements-dev.txt

### ISSUE THREAD

**Issue by thewtex** [girder/girder#1612]
I am trying to run the test suite. It appears to require cherrypy?

I installed cherrypy, but I may be encountering a version incompatibility? Here is the traceback:

```
58: Test command: /usr/bin/python-coverage "run" "--parallel-mode" "--rcfile=/home/matt/src/girder-build/tests/girder.coveragerc" "--source=girder,/home/matt/src/girder/clients/python/girder_client" "-m" "unittest" "-v" "tests.cases.py_client.lib_test"
58: Environment variables:
58:  PYTHONPATH=::/home/matt/src/girder/clients/python
58:  GIRDER_TEST_DB=mongodb://localhost:27017/girder_test_server_py_client_lib
58:  GIRDER_TEST_ASSETSTORE=server_py_client.lib
58:  GIRDER_TEST_PORT=20202
58:  GIRDER_TEST_DATA_PREFIX=/home/matt/src/girder-build/data
58: Test timeout computed to be: 1500
58: Traceback (most recent call last):
58:   File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
58:     main(module=None)
58:   File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
58:     self.parseArgs(argv)
58:   File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
58:     self.createTests()
58:   File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
58:     self.module)
58:   File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
58:     suites = [self.loadTestsFromName(name, module) for name in names]
58:   File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
58:     module = __import__('.'.join(parts_copy))
58:   File "tests/__init__.py", line 21, in <module>
58:     from girder import constants, logger
58:   File "girder/__init__.py", line 120, in <module>
58:     logger = _setupLogger()
58:   File "girder/__init__.py", line 92, in _setupLogger
58:     logPaths = getLogPaths()
58:   File "girder/__init__.py", line 74, in getLogPaths
58:     cfg = config.getConfig()
58:   File "girder/utility/config.py", line 79, in getConfig
58:     if 'database' not in cherrypy.config:
58: TypeError: argument of type 'module' is not iterable

```

Python: 2.7.12
CherryPy: 8.1.2

**Comment by zachmullen** [comment]
`requirements-dev.txt` and `requirements.txt` are disjoint, you have to install the stuff in requirements.txt via pip -r, or just do `pip install -e .[plugins]` from the girder repo directory.

**Comment by thewtex** [comment]
@zachmullen Thanks for the tip. https://github.com/girder/girder/pull/1616 also helped (I had CherryPy 8.)
