### ISSUE TITLE
Girder Worker downloadItem throws error if /tmp is on a different filesystem

### ISSUE THREAD

**Issue by kotfic** [girder/girder#1654]
Ran into this while trying to run girder_worker tests:

```
26: Traceback (most recent call last):
26:   File "/home/kotfic/kitware/projects/src/girder_worker/girder_worker/plugins/girder_io/tests/girder_io_test.py", line 227, in test_memory_targets
26:     outputs = girder_worker.run(task, inputs=inputs, outputs=outputs)
26:   File "girder_worker/utils.py", line 308, in wrapped
26:     return fn(*args, **kwargs)
26:   File "girder_worker/__init__.py", line 277, in run
26:     d, **dict({'task_input': task_input}, **kwargs))
26:   File "girder_worker/io/__init__.py", line 132, in fetch
26:     return _fetch_map[mode](spec, **kwargs)
26:   File "/home/kotfic/kitware/projects/src/girder_worker/girder_worker/plugins/girder_io/__init__.py", line 90, in fetch_handler
26:     client.downloadItem(spec['id'], kwargs['_tempdir'], filename)
26:   File "/home/kotfic/.venvs/girder/lib/python2.7/site-packages/girder_client/__init__.py", line 972, in downloadItem
26:     created=files[0]['created'])
26:   File "/home/kotfic/.venvs/girder/lib/python2.7/site-packages/girder_client/__init__.py", line 934, in downloadFile
26:     os.rename(tmp.name, path)
26: OSError: [Errno 18] Invalid cross-device link
```
i just wanted to make sure this was captured. If others run into this issue before it is closed a temporary workaround is to the export ```TMPDIR``` to a local filesystem, e.g.:

```
export TMPDIR=~/tmp/girder_client
```

**Comment by zachmullen** [comment]
The latest version of girder_client uses `shutil.move`, so this is no longer an issue.

Could you file a ticket against girder_worker to bump the version of girder_client dependency?
