### ISSUE TITLE
Fatal error: Element from loaders list with objects should have a 'loader' specified

### ISSUE THREAD

**Issue by yohanboniface** [girder/girder#1772]
- created a venv (python 3.6)
- pip install girder => OK
- girder-installl web => FAIL

As you can see in the log: python 3.6, npm 3.10.9.

```
Running "webpack:core_lib" (webpack) task
 15% building modulesFatal error: Element from loaders list with objects should have a 'loader' specified

npm ERR! Linux 4.9.6-1-ARCH
npm ERR! argv "/home/ybon/.config/fnm/bin/node" "/home/ybon/.config/fnm/bin/npm" "run" "build" "--" "--no-progress=false" "--env=prod" "--plugins="
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! girder@2.1.0 build: `grunt init && NODE_PATH=$PWD/node_modules grunt "--no-progress=false" "--env=prod" "--plugins="`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the girder@2.1.0 build script 'grunt init && NODE_PATH=$PWD/node_modules grunt "--no-progress=false" "--env=prod" "--plugins="'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the girder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt init && NODE_PATH=$PWD/node_modules grunt "--no-progress=false" "--env=prod" "--plugins="
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs girder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls girder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ybon/.virtualenvs/girder/lib/python3.6/site-packages/girder/npm-debug.log
Traceback (most recent call last):
  File "/home/ybon/.virtualenvs/girder/bin/girder-install", line 11, in <module>
    sys.exit(main())
  File "/home/ybon/.virtualenvs/girder/lib/python3.6/site-packages/girder/utility/install.py", line 318, in main
    parsed.func(parsed)
  File "/home/ybon/.virtualenvs/girder/lib/python3.6/site-packages/girder/utility/install.py", line 186, in install_web
    plugins=opts.plugins)
  File "/home/ybon/.virtualenvs/girder/lib/python3.6/site-packages/girder/utility/install.py", line 159, in runWebBuild
    (' '.join(cmd), proc.returncode))
Exception: Web client install failed: `npm run build -- --no-progress=false --env=prod --plugins=` returned 1.
```

Just wanted to have a try at girder.
Not a webpack user at all. Any hint?

**Comment by zachmullen** [comment]
Thanks @yohanboniface , I think this is a result of upstream breakages in some of our npm packages, but they have been fixed on master since. I will cut a point release tomorrow and ping this issue, then you should be able to install from pypi.

**Comment by zachmullen** [comment]
@yohanboniface I just released v2.1.1, could you upgrade to that package version and see if that fixes the issue?

**Comment by yohanboniface** [comment]
![screen shot 2017-02-06 at 22 42 52-fullpage](https://cloud.githubusercontent.com/assets/146023/22667543/7bfeac3c-ecbd-11e6-8e99-b5966cedd5a6.png)

So far, so good!
Thanks for the quick fix :)

**Comment by zachmullen** [comment]
Great!
