### ISSUE TITLE
Deleting an S3 assetstore fails if the S3 server is unreachable

### ISSUE THREAD

**Issue by manthey** [girder/girder#2161]
Steps to reproduce:
- use `tests/mock_s3.py` to create a mock S3 server.
- create an assetstore using the mock server
- stop `mock_s3.py`
- delete the assetstore

This produces a stack trace:
```
[2017-06-30 09:56:03,283] ERROR: 500 Error
Traceback (most recent call last):
  File "girder/api/rest.py", line 567, in endpointDecorator
    val = fun(self, args, kwargs)
  File "girder/api/rest.py", line 1116, in DELETE
    return self.handleRoute('DELETE', path, params)
  File "girder/api/rest.py", line 890, in handleRoute
    val = handler(**kwargs)
  File "girder/api/access.py", line 40, in wrapped
    return args[0](*iargs, **ikwargs)
  File "girder/api/describe.py", line 612, in wrapped
    return fun(*args, **kwargs)
  File "girder/api/v1/assetstore.py", line 242, in deleteAssetstore
    self.model('assetstore').remove(assetstore)
  File "girder/models/assetstore.py", line 81, in remove
    adapter.untrackedUploads([], delete=True)
  File "girder/utility/s3_assetstore_adapter.py", line 509, in untrackedUploads
    multipartUploads = self.client.list_multipart_uploads(**getParams)
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/client.py", line 586, in _make_api_call
    operation_model, request_dict)
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/ubuntu/girder/env/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
Additional info:
  Request URL: DELETE http://127.0.0.1:8086/api/v1/assetstore/5956585d1d41c83ed93e2c46
  Query string:
  Remote IP: 10.0.2.2
```

If connection to the remote server is actually required, we need a better error message.  If it isn't, this should work.

**Comment by zachmullen** [comment]
Looking at the code that is calling this in the assetstore model:

```
        try:
            adapter.untrackedUploads([], delete=True)
        except ValidationException:
            # this assetstore is currently unreachable, so skip this step
            pass
```

I guess we need to raise a ValidationException in this case, which would be eaten. If we don't want it to be eaten I guess we could raise a GirderException.

**Comment by manthey** [comment]
I think I'd choose the ValidationException and a log message.  Any partial uploads will become untracked uploads when the assetstore is unreachable and deleted.  A comment somewhere could state that reconnecting and redeleting the assetstore will clean up the untracked uploads.
