### ISSUE TITLE
Create/configure log dir in install

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#247]
Currently when trying to use an installed girder, I get an error, which according to @zachmullen seems to be from a missing log directory.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test/__init__.py", line 1, in <module>
    import web_client_test
  File "test/web_client_test.py", line 25, in <module>
    from . import base
  File "test/base.py", line 35, in <module>
    from girder.utility import model_importer
  File "/usr/local/lib/python2.7/dist-packages/girder-0.1-py2.7.egg/girder/__init__.py", line 65, in <module>
    logger = _setupLogger()
  File "/usr/local/lib/python2.7/dist-packages/girder-0.1-py2.7.egg/girder/__init__.py", line 48, in _setupLogger
    backupCount=LOG_BACKUP_COUNT)
  File "/usr/lib/python2.7/logging/handlers.py", line 118, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 65, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 897, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 916, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/girder-0.1-py2.7.egg/logs/error.log'
```

**Comment by zachmullen** [comment]
I think this must be fixed out of the box now since nobody has mentioned this lately.
