### ISSUE TITLE
Girder fails to start when pyopenssl is installed (python 3)

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#2559]
This isn't actually a Girder bug, but I thought I would make an issue in case someone else encounters it.  I believe this is specific to Python 3 only.  With the following packages installed:
```
asn1crypto==0.24.0
bcrypt==3.1.4
boto3==1.5.9
botocore==1.8.23
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
cheroot==6.0.0
CherryPy==11.0.0
click==6.7
cryptography==2.1.4
docutils==0.14
filelock==3.0.0
girder==2.4.0
idna==2.6
jmespath==0.9.3
jsonschema==2.6.0
Mako==1.0.7
MarkupSafe==1.0
more-itertools==4.0.1
portend==2.2
psutil==5.4.3
pycparser==2.18
pymongo==3.6.0
pyOpenSSL==17.5.0
python-dateutil==2.6.1
pytz==2017.3
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.12
six==1.11.0
tempora==1.10
urllib3==1.22
```
Starting Girder results in:
```
Running in mode: development
Connecting to MongoDB: mongodb://localhost:27017/girder2
Resolving plugin dependencies...
[08/Jan/2018:09:48:51] ENGINE Bus STARTING
Started asynchronous event manager thread.
[08/Jan/2018:09:48:51] ENGINE Started monitor thread '_TimeoutMonitor'.
[08/Jan/2018:09:48:51] ENGINE Started monitor thread 'Autoreloader'.
[08/Jan/2018:09:48:52] ENGINE Serving on http://0.0.0.0:8080
[08/Jan/2018:09:48:52] ENGINE Bus STARTED
[08/Jan/2018:09:48:52] ENGINE Error in background task thread function <bound method Autoreloader.run of <cherrypy.process.plugins.Autoreloader object at 0x7fc0c9962b70>>.
AttributeError: cffi library '_constant_time' has no function, constant or global variable named '__loader__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jbeezley/.virtualenvs/girder-bare/lib/python3.5/site-packages/cherrypy/process/plugins.py", line 519, in run
    self.function(*self.args, **self.kwargs)
  File "/home/jbeezley/.virtualenvs/girder-bare/lib/python3.5/site-packages/cherrypy/process/plugins.py", line 651, in run
    for filename in self.sysfiles() | self.files:
  File "/home/jbeezley/.virtualenvs/girder-bare/lib/python3.5/site-packages/cherrypy/process/plugins.py", line 635, in sysfiles
    hasattr(m, '__loader__') and
SystemError: <built-in function hasattr> returned a result with an error set

Exception in thread Autoreloader:
AttributeError: cffi library '_constant_time' has no function, constant or global variable named '__loader__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/jbeezley/.virtualenvs/girder-bare/lib/python3.5/site-packages/cherrypy/process/plugins.py", line 519, in run
    self.function(*self.args, **self.kwargs)
  File "/home/jbeezley/.virtualenvs/girder-bare/lib/python3.5/site-packages/cherrypy/process/plugins.py", line 651, in run
    for filename in self.sysfiles() | self.files:
  File "/home/jbeezley/.virtualenvs/girder-bare/lib/python3.5/site-packages/cherrypy/process/plugins.py", line 635, in sysfiles
    hasattr(m, '__loader__') and
SystemError: <built-in function hasattr> returned a result with an error set
```

This issue is fixed in a commit mentioned in https://github.com/cherrypy/cherrypy/issues/1675, but we will have to wait for https://github.com/cherrypy/cherrypy/issues/1662 to update.  The work around for the moment is to uninstall pyopenssl.

**Comment by danlamanna** [comment]
@jbeezley This doesn't happen on master, should we close? I don't see https://github.com/cherrypy/cherrypy/issues/1662 getting closed anytime soon.

**Comment by jbeezley** [comment]
We can reopen if it shows up again.
