### ISSUE TITLE
Possible write/available race condition during upload w/mongodb replicaset

### ISSUE THREAD

**Issue by nicholsn** [girder/girder#2735]
This is more of a report of an issue I think I have resolved and a request to possibly provide a better error message for mongo replicasets. 

When using the girder-cli to upload a folder to a gridfs assetstore, I kept getting errors like the following:

```
girder-cli --api-url http://localhost:5000/girder/api/v1 --api-key <key> --retries 5 upload 5af23e58bf2307ac9e0a54b9 submissions
Creating Folder from submissions
[####################################]  110.00k/110.00k  100%  submission.tar
Traceback (most recent call last):
  File "/usr/local/bin/girder-cli", line 9, in <module>
    load_entry_point('girder-client==2.3.0', 'console_scripts', 'girder-cli')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/girder_client-2.3.0-py2.7.egg/girder_client/cli.py", line 366, in _upload
    blacklist=blacklist.split(','), dryRun=dry_run, reference=reference)
  File "/usr/local/lib/python2.7/dist-packages/girder_client-2.3.0-py2.7.egg/girder_client/__init__.py", line 1727, in upload
    blacklist=blacklist, dryRun=dryRun, reference=reference)
  File "/usr/local/lib/python2.7/dist-packages/girder_client-2.3.0-py2.7.egg/girder_client/__init__.py", line 1668, in _uploadFolderRecursive
    reference=reference)
  File "/usr/local/lib/python2.7/dist-packages/girder_client-2.3.0-py2.7.egg/girder_client/__init__.py", line 1574, in _uploadAsItem
    parentFolderId, filePath, filename=localFile, reference=reference)
  File "/usr/local/lib/python2.7/dist-packages/girder_client-2.3.0-py2.7.egg/girder_client/__init__.py", line 997, in uploadFileToFolder
    progressCallback)
  File "/usr/local/lib/python2.7/dist-packages/girder_client-2.3.0-py2.7.egg/girder_client/__init__.py", line 954, in uploadStreamToFolder
    'file', params, data=_ProgressBytesIO(chunk, reporter=reporter))
  File "/usr/local/lib/python2.7/dist-packages/girder_client-2.3.0-py2.7.egg/girder_client/__init__.py", line 511, in post
    data=data, json=json, headers=headers, jsonResp=jsonResp)
  File "/usr/local/lib/python2.7/dist-packages/girder_client-2.3.0-py2.7.egg/girder_client/cli.py", line 104, in sendRestRequest
    return super(GirderCli, self).sendRestRequest(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/girder_client-2.3.0-py2.7.egg/girder_client/__init__.py", line 497, in sendRestRequest
    response=result)
girder_client.HttpError: HTTP error 500: POST http://localhost:5000/girder/api/v1/file?mimeType=application%2Fx-tar&parentType=folder&size=112640&name=410177417d27eb21b654d7b03150df5592560dec846454b0e3c08be89233608b.tar&parentId=5af5f6bcbf2307ac9e0a55ce
Response text: {"message": "TypeError: TypeError(\"'NoneType' object has no attribute '__getitem__'\",)", "type": "internal"}
```
On the serverside, I would see errors like the following:

```
[2018-06-08 09:58:10,400] ERROR: CherryPy Checker:
[2018-06-08 09:58:10,400] ERROR: The config entry 'server.socket_host' in section 'server.socket_host' is of type 'unicode', which does not match the expected type 'str'.
[2018-06-08 10:02:21,332] ERROR: 500 Error
Traceback (most recent call last):
  File "/usr/local/girder/girder-master/girder/api/rest.py", line 593, in endpointDecorator
    val = fun(self, args, kwargs)
  File "/usr/local/girder/girder-master/girder/api/rest.py", line 1176, in POST
    return self.handleRoute(method, path, params)
  File "/usr/local/girder/girder-master/girder/api/rest.py", line 919, in handleRoute
    val = handler(**kwargs)
  File "/usr/local/girder/girder-master/girder/api/access.py", line 63, in wrapped
    return fun(*args, **kwargs)
  File "/usr/local/girder/girder-master/girder/api/describe.py", line 709, in wrapped
    return fun(*args, **kwargs)
  File "/usr/local/girder/girder-master/girder/api/v1/file.py", line 150, in initUpload
    return Upload().handleChunk(upload, chunk, filter=True, user=user)
  File "/usr/local/girder/girder-master/girder/models/upload.py", line 156, in handleChunk
    file = self.finalizeUpload(upload, assetstore)
  File "/usr/local/girder/girder-master/girder/models/upload.py", line 242, in finalizeUpload
    file = File().save(file)
  File "/usr/local/girder/girder-master/girder/models/model_base.py", line 442, in save
    events.trigger('model.%s.save.created' % self.name, document)
  File "/usr/local/girder/girder-master/girder/events.py", line 314, in trigger
    handler['handler'](e)
  File "/usr/local/girder/girder-master/girder/models/file.py", line 365, in _propagateSizeToItem
    self.propagateSizeChange(item, fileDoc['size'])
  File "/usr/local/girder/girder-master/girder/models/file.py", line 282, in propagateSizeChange
    '_id': item['_id']
TypeError: 'NoneType' object has no attribute '__getitem__'
Additional info:
  Request URL: POST http://localhost:5000/girder/api/v1/file
  Query string: mimeType=application%2Fjson&parentType=folder&size=4388&name=metadata.json&parentId=5b1ab69dbf23078ba7029b1e
```

This lead me to the following issue: https://github.com/girder/girder/issues/2378

This issue indicated that mongodb replicasets might be the culprit and after updating the read preference to primary, the issue seems to have resolved itself.

```
[database]
...
readPreference = "primaryPreferred"
```

Does this solution make sense? Or is there a better way to handle this?

**Comment by manthey** [comment]
I think this is a mongo configuration concern and outside the scope of girder's process
