### ISSUE TITLE
Error using gider-cli

### ISSUE THREAD

**Issue by bpaniagua** [girder/girder#3121]
When using girder-cli in MacOS (10.14.6)
girder-cli --username [...] --api-key [...] --api-url https://data.kitware.com/api/v1 upload [...] [folder]

I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/girder-cli", line 6, in <module>
    from girder_client.cli import main
  File "/Library/Python/2.7/site-packages/girder_client/cli.py", line 7, in <module>
    from six.moves.http_client import HTTPConnection
ImportError: No module named http_client

**Comment by danlamanna** [comment]
Is that the complete error message?

**Comment by bpaniagua** [comment]
Yes. I just tested this problem does not occur in Linux Ubuntu 16.04

**Comment by danlamanna** [comment]
If you reinstall girder-client, `pip install --upgrade girder-client`. Does the issue persist?

**Comment by bpaniagua** [comment]
Yes.


I just did a fresh girder-client installation this morning, this is a new computer.

**Comment by danlamanna** [comment]
Mind trying something like this:
```
pip install --user girder-client
~/Library/Python/2.7/bin/girder-cli --username [...] --api-key [...] --api-url https://data.kitware.com/api/v1 upload [...] [folder]
```

**Comment by bpaniagua** [comment]
girder-cli does not seem to be installed there...

**Comment by manthey** [comment]
This appears stale
