### ISSUE TITLE
Error with "dnspython" module not installed

### ISSUE THREAD

**Issue by Stegosource** [girder/girder#3189]
Trying to run Girder from the Docker container as per the docs (https://girder.readthedocs.io/en/stable/deploy.html#docker-container). I'm using MongoDB Atlas as my remote database, but I keep getting an error about the missing `dnspython` module.

Here's the stack trace:

```
Running in mode: production
Traceback (most recent call last):
  File "/usr/local/bin/girder", line 11, in <module>
    load_entry_point('girder', 'console_scripts', 'girder')()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/girder/girder/cli/serve.py", line 41, in main
    server.setup(mode)
  File "/girder/girder/utility/server.py", line 154, in setup
    girderWebroot, appconf = configureServer(mode, plugins, curConfig)
  File "/girder/girder/utility/server.py", line 81, in configureServer
    api_main.addApiToNode(root)
  File "/girder/girder/api/api_main.py", line 20, in addApiToNode
    _addV1ToNode(node.api)
  File "/girder/girder/api/api_main.py", line 30, in _addV1ToNode
    node.v1.assetstore = assetstore.Assetstore()
  File "/girder/girder/api/v1/assetstore.py", line 23, in __init__
    self._model = AssetstoreModel()
  File "/girder/girder/models/model_base.py", line 71, in __call__
    cls._instance = super(_ModelSingleton, cls).__call__(*args, **kwargs)
  File "/girder/girder/models/model_base.py", line 105, in __init__
    self.reconnect()
  File "/girder/girder/models/model_base.py", line 112, in reconnect
    db_connection = getDbConnection()
  File "/girder/girder/models/__init__.py", line 89, in getDbConnection
    client = pymongo.MongoClient(uri, **clientOptions)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/mongo_client.py", line 621, in __init__
    connect_timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/uri_parser.py", line 390, in parse_uri
    raise ConfigurationError('The "dnspython" module must be '
pymongo.errors.ConfigurationError: The "dnspython" module must be installed to use mongodb+srv:// URIs
```

**Comment by danlamanna** [comment]
How are you configuring the database URI? Is it possible to drop the `+srv` portion of the URI?

**Comment by Stegosource** [comment]
I'm using the connection string provided by MongoDB Atlas. Removing the `+srv` part causes the database connection to time out.

But I also realized that the Docker image may not be what I want, because I will need to install Girder plugins, which would not be part of the image, right?

**Comment by danlamanna** [comment]
> But I also realized that the Docker image may not be what I want, because I will need to install Girder plugins, which would not be part of the image, right?

Correct. Your best bet is likely to inherit from the `girder/girder` docker image in order to add `dnspython` and any deployment-specific configuration.

**Comment by Stegosource** [comment]
Oh yeah. I was thinking I would go at it from scratch, but inheriting from the girder/girder image is a good tip
