### ISSUE TITLE
Docker compose up fails

### ISSUE THREAD

**Issue by luissv7** [girder/girder#3305]
ERROR: Service 'girder' failed to build: The command '/bin/sh -c pip install --upgrade --upgrade-strategy eager --editable .' returned a non-zero code: 1

**Comment by Gjacquenot** [comment]
For time being, this specific command works with [SHA](https://github.com/girder/girder/commit/4e4ca0aaee0307531d572fecce8acb3aaba8f4e4). 

However, the next does not...

```
Step 12/13 : RUN girder build
 ---> Running in f7793f217cd8
Traceback (most recent call last):
  File "/usr/bin/girder", line 33, in <module>
    sys.exit(load_entry_point('girder', 'console_scripts', 'girder')())
  File "/usr/bin/girder", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 947, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 538, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for girder
The command '/bin/sh -c girder build' returned a non-zero code: 1
```

It would be nice to fix this and make a docker build in the CI!

**Comment by Gjacquenot** [comment]
@manthey , for your information... If you have any idea...

**Comment by zachmullen** [comment]
Hi @Gjacquenot , thanks for the stack trace. If you manage to track down a fix, a PR would be welcome.

**Comment by fepegar** [comment]
Should this be closed now?

**Comment by Gjacquenot** [comment]
Yes! It can be closed! Thanks @zachmullen @fepegar
