### ISSUE TITLE
girder-client not compatible with click 8.0

### ISSUE THREAD

**Issue by brittonsmith** [girder/girder#3357]
As of a week or so ago, I get the following error when using`girder-client`:
```
Traceback (most recent call last):
  File "/home/circleci/venv/bin/girder-cli", line 8, in <module>
    sys.exit(main())
  File "/home/circleci/venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/circleci/venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/circleci/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/circleci/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/circleci/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/circleci/venv/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/circleci/venv/lib/python3.9/site-packages/girder_client/cli.py", line 323, in _download
    gc.downloadResource(parent_id, local_folder, parent_type)
  File "/home/circleci/venv/lib/python3.9/site-packages/girder_client/__init__.py", line 1402, in downloadResource
    self.downloadFolderRecursive(folder['_id'], local, sync=sync)
  File "/home/circleci/venv/lib/python3.9/site-packages/girder_client/__init__.py", line 1363, in downloadFolderRecursive
    self.downloadItem(item['_id'], dest, name=item['name'])
  File "/home/circleci/venv/lib/python3.9/site-packages/girder_client/__init__.py", line 1296, in downloadItem
    self.downloadFile(
  File "/home/circleci/venv/lib/python3.9/site-packages/girder_client/__init__.py", line 1232, in downloadFile
    with self.progressReporterCls(
  File "/home/circleci/venv/lib/python3.9/site-packages/click/_termui_impl.py", line 98, in __enter__
    self.render_progress()
  File "/home/circleci/venv/lib/python3.9/site-packages/click/_termui_impl.py", line 242, in render_progress
    line = self.format_progress_line()
  File "/home/circleci/venv/lib/python3.9/site-packages/click/_termui_impl.py", line 193, in format_progress_line
    info_bits.append(self.format_pos())
  File "/home/circleci/venv/lib/python3.9/site-packages/girder_client/cli.py", line 74, in formatPos
    if _self.length_known:
AttributeError: 'ProgressBar' object has no attribute 'length_known'
```

I've narrowed this down to an update with the `click` module. The `length_known` attribute was removed as of version 8.0. From looking at how `length_known` was implemented, I think this can be fixed by changing the last line in the traceback to:
```
if _self.length is not None:
```

**Comment by jbeezley** [comment]
Thanks for the fix.  I'm moving this change over to #3359 to include another change that fixes the tests.

**Comment by brittonsmith** [comment]
Great, thanks very much!
