### ISSUE TITLE
Can't set up a development environment

### ISSUE THREAD

**Issue by fepegar** [girder/girder#3384]
Hi again. I am trying to set up a development environment to add Microsoft Azure as an OAuth provider.
I have tried the methods in [Developer Guide](https://girder.readthedocs.io/en/latest/development.html) and [Developer Installation](https://girder.readthedocs.io/en/latest/dev-installation.html), with no luck. I am on Ubuntu 18.04.

Do you know what could be going on?

Below are the outputs for the two methods.

### Vagrant (Developer Guide)

```console
$ vagrant up
[...]
TASK [ansible-role-girder : Install Girder] ************************************
fatal: [default]: FAILED! => {"changed": false, "cmd": ["/home/vagrant/.virtualenvs/girder/bin/pip3", "install", "-U", "--pre", "-e", "/home/vagrant/girder"], "msg": "stdout: Obtaining file:///home/vagrant/girder\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'error'\n\n:stderr:   ERROR: Command errored out with exit status 1:\n   command: /home/vagrant/.virtualenvs/girder/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/home/vagrant/girder/setup.py'\"'\"'; __file__='\"'\"'/home/vagrant/girder/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-j5gbs2v2\n       cwd: /home/vagrant/girder/\n  Complete output (33 lines):\n  Traceback (most recent call last):\n    File \"<string>\", line 1, in <module>\n    File \"/home/vagrant/girder/setup.py\", line 95, in <module>\n      'build = girder.cli.build:main'\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/__init__.py\", line 128, in setup\n      _install_setup_requires(attrs)\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/__init__.py\", line 123, in _install_setup_requires\n      dist.fetch_build_eggs(dist.setup_requires)\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/dist.py\", line 513, in fetch_build_eggs\n      replace_conflicting=True,\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 774, in resolve\n      replace_conflicting=replace_conflicting\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 1057, in best_match\n      return self.obtain(req, installer)\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 1069, in obtain\n      return installer(requirement)\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/dist.py\", line 580, in fetch_build_egg\n      return cmd.easy_install(req)\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/command/easy_install.py\", line 698, in easy_install\n      return self.install_item(spec, dist.location, tmpdir, deps)\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/command/easy_install.py\", line 724, in install_item\n      dists = self.install_eggs(spec, download, tmpdir)\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/command/easy_install.py\", line 874, in install_eggs\n      return [self.install_wheel(dist_filename, tmpdir)]\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/command/easy_install.py\", line 1092, in install_wheel\n      os.path.dirname(destination)\n    File \"/usr/lib/python3.6/distutils/cmd.py\", line 335, in execute\n      util.execute(func, args, msg, dry_run=self.dry_run)\n    File \"/usr/lib/python3.6/distutils/util.py\", line 301, in execute\n      func(*args)\n    File \"/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/wheel.py\", line 123, in install_as_egg\n      os.path.join(egg_info, 'PKG-INFO'))\n  FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/girder/.eggs/setuptools_scm-6.4.2-py3.6.egg/EGG-INFO/METADATA' -> '/home/vagrant/girder/.eggs/setuptools_scm-6.4.2-py3.6.egg/EGG-INFO/PKG-INFO'\n  ----------------------------------------\nWARNING: Discarding file:///home/vagrant/girder. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\nERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n"}

RUNNING HANDLER [girder.mongodb : Restart MongoDB] *****************************

PLAY RECAP *********************************************************************
default                    : ok=19   changed=16   unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I've beautified the error message:

```python-traceback
stdout: Obtaining file:///home/vagrant/girder
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

:stderr:   ERROR: Command errored out with exit status 1:
   command: /home/vagrant/.virtualenvs/girder/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/vagrant/girder/setup.py'"'"'; __file__='"'"'/home/vagrant/girder/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-j5gbs2v2
       cwd: /home/vagrant/girder/
  Complete output (33 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/vagrant/girder/setup.py", line 95, in <module>
      'build = girder.cli.build:main'
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
      _install_setup_requires(attrs)
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
      replace_conflicting=True,
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
      replace_conflicting=replace_conflicting
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1057, in best_match
      return self.obtain(req, installer)
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1069, in obtain
      return installer(requirement)
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
      return cmd.easy_install(req)
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 698, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 724, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 874, in install_eggs
      return [self.install_wheel(dist_filename, tmpdir)]
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1092, in install_wheel
      os.path.dirname(destination)
    File "/usr/lib/python3.6/distutils/cmd.py", line 335, in execute
      util.execute(func, args, msg, dry_run=self.dry_run)
    File "/usr/lib/python3.6/distutils/util.py", line 301, in execute
      func(*args)
    File "/home/vagrant/.virtualenvs/girder/lib/python3.6/site-packages/setuptools/wheel.py", line 123, in install_as_egg
      os.path.join(egg_info, 'PKG-INFO'))
  FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/girder/.eggs/setuptools_scm-6.4.2-py3.6.egg/EGG-INFO/METADATA' -> '/home/vagrant/girder/.eggs/setuptools_scm-6.4.2-py3.6.egg/EGG-INFO/PKG-INFO'
  ----------------------------------------
WARNING: Discarding file:///home/vagrant/girder. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### PIP (Developer Installation)

```console
$ pip install -r requirements-dev.txt
  Building wheel for python-ldap (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/fernando/miniconda3/envs/dsa/bin/python /home/fernando/miniconda3/envs/dsa/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpx5whp3j_
       cwd: /tmp/pip-install-mejocxs3/python-ldap_e94a70e292564c99ad9e5457df0822fc
  Complete output (83 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  copying Lib/ldapurl.py -> build/lib.linux-x86_64-3.8
  copying Lib/ldif.py -> build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/ldapobject.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/__init__.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/compat.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/modlist.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/asyncsearch.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/cidict.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/syncrepl.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/async.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/filter.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/pkginfo.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/functions.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/resiter.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/constants.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/logger.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/dn.py -> build/lib.linux-x86_64-3.8/ldap
  copying Lib/ldap/sasl.py -> build/lib.linux-x86_64-3.8/ldap
  creating build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/__init__.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/psearch.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/openldap.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/readentry.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/simple.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/pagedresults.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/ppolicy.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/sessiontrack.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/libldap.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/pwdpolicy.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/deref.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/sss.py -> build/lib.linux-x86_64-3.8/ldap/controls
  copying Lib/ldap/controls/vlv.py -> build/lib.linux-x86_64-3.8/ldap/controls
  creating build/lib.linux-x86_64-3.8/ldap/extop
  copying Lib/ldap/extop/__init__.py -> build/lib.linux-x86_64-3.8/ldap/extop
  copying Lib/ldap/extop/dds.py -> build/lib.linux-x86_64-3.8/ldap/extop
  copying Lib/ldap/extop/passwd.py -> build/lib.linux-x86_64-3.8/ldap/extop
  creating build/lib.linux-x86_64-3.8/ldap/schema
  copying Lib/ldap/schema/__init__.py -> build/lib.linux-x86_64-3.8/ldap/schema
  copying Lib/ldap/schema/models.py -> build/lib.linux-x86_64-3.8/ldap/schema
  copying Lib/ldap/schema/subentry.py -> build/lib.linux-x86_64-3.8/ldap/schema
  copying Lib/ldap/schema/tokenizer.py -> build/lib.linux-x86_64-3.8/ldap/schema
  creating build/lib.linux-x86_64-3.8/slapdtest
  copying Lib/slapdtest/__init__.py -> build/lib.linux-x86_64-3.8/slapdtest
  copying Lib/slapdtest/_slapdtest.py -> build/lib.linux-x86_64-3.8/slapdtest
  running egg_info
  writing Lib/python_ldap.egg-info/PKG-INFO
  writing dependency_links to Lib/python_ldap.egg-info/dependency_links.txt
  writing requirements to Lib/python_ldap.egg-info/requires.txt
  writing top-level names to Lib/python_ldap.egg-info/top_level.txt
  reading manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'Doc/.build'
  adding license file 'LICENCE'
  writing manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
  creating build/lib.linux-x86_64-3.8/slapdtest/certs
  copying Lib/slapdtest/certs/README -> build/lib.linux-x86_64-3.8/slapdtest/certs
  copying Lib/slapdtest/certs/ca.conf -> build/lib.linux-x86_64-3.8/slapdtest/certs
  copying Lib/slapdtest/certs/ca.pem -> build/lib.linux-x86_64-3.8/slapdtest/certs
  copying Lib/slapdtest/certs/client.conf -> build/lib.linux-x86_64-3.8/slapdtest/certs
  copying Lib/slapdtest/certs/client.key -> build/lib.linux-x86_64-3.8/slapdtest/certs
  copying Lib/slapdtest/certs/client.pem -> build/lib.linux-x86_64-3.8/slapdtest/certs
  copying Lib/slapdtest/certs/gencerts.sh -> build/lib.linux-x86_64-3.8/slapdtest/certs
  copying Lib/slapdtest/certs/gennssdb.sh -> build/lib.linux-x86_64-3.8/slapdtest/certs
  copying Lib/slapdtest/certs/server.conf -> build/lib.linux-x86_64-3.8/slapdtest/certs
  copying Lib/slapdtest/certs/server.key -> build/lib.linux-x86_64-3.8/slapdtest/certs
  copying Lib/slapdtest/certs/server.pem -> build/lib.linux-x86_64-3.8/slapdtest/certs
  running build_ext
  building '_ldap' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/Modules
  gcc -pthread -B /home/fernando/miniconda3/envs/dsa/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 "-DLDAPMODULE_AUTHOR=python-ldap project" "-DLDAPMODULE_LICENSE=Python style" -IModules -I/home/fernando/miniconda3/envs/dsa/include/python3.8 -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.8/Modules/LDAPObject.o
  In file included from Modules/LDAPObject.c:3:0:
  Modules/common.h:15:10: fatal error: lber.h: No such file or directory
   #include <lber.h>
            ^~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for python-ldap
  Building wheel for sentinels (setup.py) ... done
  Created wheel for sentinels: filename=sentinels-1.0.0-py3-none-any.whl size=3200 sha256=8de551565f657c7b68b36832bb6313727937cac787fc2cf47cff00506610a47f
  Stored in directory: /home/fernando/.cache/pip/wheels/52/6d/1d/f8b21b7cc5b50cba5e5744c06f71fdac7d7464cb6f35e61abf
Successfully built configparser girder-worker girder girder-client girder-worker-utils jsondiff future sentinels
Failed to build python-ldap
ERROR: Could not build wheels for python-ldap which use PEP 517 and cannot be installed directly
```
```

**Comment by fepegar** [comment]
Thanks, @manthey. The command has now worked. I will try the rest of the steps and keep you posted.

**Comment by fepegar** [comment]
I'm getting a new error, this time `npm`-related:

```console
$ girder build --dev
npm WARN deprecated extract-text-webpack-plugin@2.1.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated swagger-ui@2.2.10: No longer maintained, please upgrade to swagger-ui@3.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated core-js@2.3.0: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! Linux 4.18.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:109:7
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.18.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fernando/miniconda3/envs/dsa/lib/python3.8/site-packages/girder/web_client/npm-debug.log
Traceback (most recent call last):
  File "/home/fernando/miniconda3/envs/dsa/bin/girder", line 8, in <module>
    sys.exit(main())
  File "/home/fernando/miniconda3/envs/dsa/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/fernando/miniconda3/envs/dsa/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/fernando/miniconda3/envs/dsa/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fernando/miniconda3/envs/dsa/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fernando/miniconda3/envs/dsa/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/fernando/miniconda3/envs/dsa/lib/python3.8/site-packages/girder/cli/build.py", line 83, in main
    check_call(installCommand, cwd=staging)
  File "/home/fernando/miniconda3/envs/dsa/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1.
```

**Comment by manthey** [comment]
Probably you need an older version of node.  The girder build script (currently) doesn't work on node versions newer than 12.x.

**Comment by fepegar** [comment]
> Probably you need an older version of node. The girder build script (currently) doesn't work on node versions newer than 12.x.

I'm not sure I understand. The error message shows I'm using `node v8.10.0`.
