### ISSUE TITLE
NPM error when building girder Docker image

### ISSUE THREAD

**Issue by fepegar** [girder/girder#3390]
I'm getting an error today that I wasn't getting yesterday and I suspect it's related to
- #3389

Here are the last lines of ` /root/.npm/_logs/2022-03-23T11_36_11_184Z-debug.log`:

```
23050 silly saveTree │   ├─┬ os-locale@1.4.0
23050 silly saveTree │   │ └─┬ lcid@1.0.0
23050 silly saveTree │   │   └── invert-kv@1.0.0
23050 silly saveTree │   ├── require-main-filename@1.0.1
23050 silly saveTree │   ├── string-width@1.0.2
23050 silly saveTree │   ├── which-module@1.0.0
23050 silly saveTree │   ├── y18n@3.2.2
23050 silly saveTree │   └── yargs-parser@4.2.1
23050 silly saveTree └── whatwg-fetch@2.0.4
23051 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
23052 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
23053 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
23053 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
23053 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
23053 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
23054 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
23055 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
23056 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
23056 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
23056 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
23056 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
23057 warn backbone.localstorage@2.1.0 requires a peer of backbone@1.3.3 but none is installed. You must install peer dependencies yourself.
23058 warn vtk.js@23.2.0 requires a peer of wslink@^1.1.0 but none is installed. You must install peer dependencies yourself.
23059 warn worker-loader@3.0.8 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
23060 warn ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
23061 verbose stack Error: @girder/fontello@3.1.9 preinstall: `npm-force-resolutions`
23061 verbose stack spawn ENOENT
23061 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
23061 verbose stack     at ChildProcess.emit (events.js:314:20)
23061 verbose stack     at maybeClose (internal/child_process.js:1022:16)
23061 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23062 verbose pkgid @girder/fontello@3.1.9
23063 verbose cwd /opt/girder/girder/web_client
23064 verbose Linux 5.4.0-1072-azure
23065 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
23066 verbose node v12.22.11
23067 verbose npm  v6.14.16
23068 error code ELIFECYCLE
23069 error syscall spawn
23070 error file sh
23071 error errno ENOENT
23072 error @girder/fontello@3.1.9 preinstall: `npm-force-resolutions`
23072 error spawn ENOENT
23073 error Failed at the @girder/fontello@3.1.9 preinstall script.
23073 error This is probably not a problem with npm. There is likely additional logging output above.
23074 verbose exit [ 1, true ]
```

**Comment by fepegar** [comment]
Actually I get the error when running `docker-compose` for the DSA, but I just realized I might be wrong, as I am pulling my own fork of `girder` for the image. However, I wasn't getting this error yesterday...

**Comment by fepegar** [comment]
I suppose it's due to the changes in the `fontello` package, which is being pulled from somewhere else by `npm`.

**Comment by fepegar** [comment]
The build is successful when I use `"@girder/fontello": "3.1.3",` instead of

https://github.com/girder/girder/blob/50bb6bcad9c6763db3174c916d16adabb2caafb6/girder/web_client/src/package.json#L20

**Comment by fepegar** [comment]
Build completed correctly this time. Thanks, @manthey.
