### ISSUE TITLE
Babel 7 supported plugin

### ISSUE THREAD

**Issue by tymiao1220** [girder/girder#3413]
I am about to develop an image viewer plugin using itk-wasm, and have the package.js as following, 
```
{
    "name": "@girder/itkvtkviewer",
    "description": "A Python and REST API for Medical Image Viewer",
    "version": "0.1.0",
    "homepage": "https://github.com/csef/Medical_image_viwer",
    "license": "Apache-2.0",
    "repository": {
        "type": "git",
        "url": "https://github.com/csef/Medical_image_viwer"
    },
    "scripts": {
        "lint": "eslint . && pug-lint . && stylint"
    },
    "peerDependencies": {
        "@girder/core": "*"
    },
    "dependencies": {
        "itk-vtk-viewer": "^14.3.0",
        "@kitware/vtk.js": "^24.14.2",
        "vtk.js": "^24.14.2",
        "@babel/core": "^7.14.6",
        "@babel/preset-env": "^7.14.7",
        "@babel/plugin-transform-runtime": "^7.13.6"
    },
    "devDependencies": {
        "@babel/core": "^7.14.6",
        "@babel/plugin-transform-runtime": "^7.13.6",
        "@babel/preset-env": "^7.14.7",
        "babel-loader": "^8.2.2",
        "worker-loader": "^3.0.8"
    },
    "main": "./index.js",
    "girderPlugin": {
        "name": "itkvtkviewer",
        "main": "./main.js",
        "webpack": "webpack.helper"
    }
}
```
whenever I try to build the client code by girder build --dev, I got error saying
```
Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
at throwVersionError (/admin/Radiology_viewer/girder_itkvtkviewer/web_client/node_modules/@babel/helper-plugin-utils/lib/index.js:83:11)
    at Object.assertVersion (/admin/Radiology_viewer/girder_itkvtkviewer/web_client/node_modules/@babel/helper-plugin-utils/lib/index.js:31:5)
    at /admin/Radiology_viewer/girder_itkvtkviewer/web_client/node_modules/@babel/plugin-transform-runtime/lib/index.js:34:7
    at /admin/Radiology_viewer/girder_itkvtkviewer/web_client/node_modules/@babel/helper-plugin-utils/lib/index.js:23:12
    at Function.memoisePluginContainer (/admin/env/test/lib/python3.6/site-packages/girder/web_client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/admin/env/test/lib/python3.6/site-packages/girder/web_client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /admin/env/test/lib/python3.6/site-packages/girder/web_client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/admin/env/test/lib/python3.6/site-packages/girder/web_client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/admin/env/test/lib/python3.6/site-packages/girder/web_client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/admin/env/test/lib/python3.6/site-packages/girder/web_client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/admin/env/test/lib/python3.6/site-packages/girder/web_client/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/admin/env/test/lib/python3.6/site-packages/girder/web_client/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/admin/env/test/lib/python3.6/site-packages/girder/web_client/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/admin/env/test/lib/python3.6/site-packages/girder/web_client/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/admin/env/test/lib/python3.6/site-packages/girder/web_client/node_modules/babel-loader/lib/index.js:173:20)
 @ ./~/@girder/itkvtkviewer/views/ITKVTKViewer.js 730:38-57
 @ ./~/@girder/itkvtkviewer/views/index.js
 @ ./~/@girder/itkvtkviewer/index.js
 @ ./~/@girder/itkvtkviewer/main.js
 @ dll plugins/itkvtkviewer/plugin
```
it seems it is always looking for babel version 6.26.3 that installed when install girder web not the one this plugin installed, is there a way to use the babel 7 that is installed for this particular plugin. 
Thanks for any help.

**Comment by manthey** [comment]
Outdated with Girder 5
