### ISSUE TITLE
Grunt does not seem to install pluging npm dependencies

### ISSUE THREAD

**Issue by pchoisel** [girder/girder#3444]
When building Girder's web interface with the dicom-viewer plugin installed, some packages are missing to complete the build process.

Steps to reproduce:

```shell
pip install girder girder-dicom-viewer
girder build
```

This gives the error:

 ```
Loading "build.js" tasks...ERROR
>> Error: Cannot find module 'shader-loader'
>> Require stack:
>> - /home/user/env/lib/python3.8/site-packages/girder_dicom_viewer/web_client/webpack.helper.js
>> - /home/user/env/lib/python3.8/site-packages/girder/web_client/grunt_tasks/build.js
>> - /home/user/env/lib/python3.8/site-packages/girder/web_client/node_modules/grunt/lib/grunt/task.js
>> - /home/user/env/lib/python3.8/site-packages/girder/web_client/node_modules/grunt/lib/grunt.js
>> - /home/user/env/lib/python3.8/site-packages/girder/web_client/node_modules/grunt-cli/bin/grunt
>> - /home/user/env/lib/python3.8/site-packages/girder/web_client/node_modules/grunt/bin/grunt
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.
Traceback (most recent call last):
  File "/home/user/env/bin/girder", line 8, in <module>
    sys.exit(main())
  File "/home/user/env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/env/lib/python3.8/site-packages/girder/cli/build.py", line 104, in main
    check_call(buildCommand, cwd=staging)
  File "/home/user/.pyenv/versions/3.8.10/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build', '--', '--girder-version=3.1.17', '--static-path=/home/user/env/share/girder/static', '--static-public-path=/static', '--no-progress=false', '--env=prod']' returned non-zero exit status 3.
```

However, by installing the dependencies of girder-dicom-viewer, the build process completes successfully:

```
npm install shader-loader vtk.js@5.10.3 daikon babel-preset-env
```

The issue seems to come from Grunt, but I don't know where to look. Do you have any idea ?

**Comment by manthey** [comment]
This is probably an npm/node version issue.  You need node <= 14.x and npm <= 6.x to build the girder client.

**Comment by manthey** [comment]
Modifying that would be great.  We have plans to update things to support modern node versions, but we have to sort out some of the tests before we can do it.  In the meantime, we should update the docs.
