### ISSUE TITLE
girder_client - Fail to upload data when assestore is a S3 bucket

### ISSUE THREAD

**Issue by jcfr** [girder/girder#912]
@mgrauer and I could reproduce the issue on challenge.kitware.com and also on an instance using girder master.

The client has been installed using `pip install girder_client`

```
$ girder-cli --host challenge.kitware.com --scheme https --port 443  --parent-type folder 5519921acad3a55533264fd5 TCGA-17-Z011
[...]
Creating Folder from TCGA-17-Z011
Uploading Item from 000005 Unknown-label.nrrd
Uploading Item from 000005 Unknown.nrrd
Traceback (most recent call last):
  File "/home/jcfr/.virtualenvs/girder/bin/girder-cli", line 9, in <module>
    load_entry_point('girder-client==1.0.0', 'console_scripts', 'girder-cli')()
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/cli.py", line 96, in main
    reuse_existing=args.reuse)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 895, in upload
    leaf_folders_as_items, reuse_existing)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 852, in _upload_folder_recursive
    entry, folder['_id'], full_entry, reuse_existing)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 758, in _upload_as_item
    local_file, current_item['_id'], file_path)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 741, in _upload_file_to_item
    self.uploadFileToItem(parent_item_id, file_path)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 470, in uploadFileToItem
    obj = self.post(path, parameters=parameters, files=filedata)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 220, in post
    return self.sendRestRequest('POST', path, parameters, files=files)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 214, in sendRestRequest
    text=result.text)
girder_client.HttpError: HTTP error 413: POST https://challenge.kitware.com:443/api/v1/file/chunk?uploadId=55c54128cad3a565738a9f17&offset=0
```

**Comment by jcfr** [comment]
Details about the files:

```
(girder)jcfr@karakoram:TCGA-17-Z011 $ ls -alsh 
total 9.8M
4.0K drwxrwxr-x  2 jcfr jcfr 4.0K Aug  7 18:26 .
 16K drwxrwxr-x 58 jcfr jcfr  12K Aug  7 18:25 ..
 32K -rwxrwxr-x  1 jcfr jcfr  17K Mar  5 14:44 000005 Unknown-label.nrrd
9.8M -rwxrwxr-x  1 jcfr jcfr 9.8M Mar  3 11:42 000005 Unknown.nrrd
```

**Comment by mgrauer** [comment]
After a bit of digging, we are getting 413 from nginx.  We need to update our nginx site config in covalic ansible (which you used as the basis for your work) to add this to our `location`

    client_max_body_size some_number_of_bytes;

Probably makes sense to ensure this is the same [value as in the girder-client](https://github.com/girder/girder/blob/master/clients/python/girder_client/__init__.py#L97).

At this point, the error switched to a 500, and there was nothing in the nginx logs since this was coming from Girder.  Another problem I found in our ansible config is that we aren't setting our permissions correctly (or perhaps we should change our log location for Girder in that provisioning) and error.log can't be written.

After tweaking the perms to write out error.log, I can see the error is happening in the [s3_assetstore_adapter](https://github.com/girder/girder/blob/master/girder/utility/s3_assetstore_adapter.py#L229-L231), with S3 returning an error code 104.  This looks like a known issue in [boto](https://github.com/boto/boto/issues/2207), and I didn't get time to dig into the solutions deeply.  [This one did not work](https://github.com/boto/boto/issues/2207#issuecomment-103687364).  Perhaps we can try playing around with specifying region/location like [this suggestion](https://github.com/boto/boto/issues/2207#issuecomment-60682869) ? 

@jcfr , didn't you and @cpatrick run into trouble setting up your S3 bucket in some way, with respect to specifying region?  Could be a related change in their API for S3.

**Comment by jcfr** [comment]
@mgrauer  Thanks for your help with this. After setting up the  `client_max_body_size` to `134217728`. See https://github.com/crad/infrastructure/commit/ba80360d33e9833d1b1d36b834db74137ba51e9b

Upload is failing with file around 32M

```
$ girder-cli --user jcfr --host <hostname> --port 80 --parent-type collection 55c537c656d1f32fbab4de75 ./girder-bug/
Password for jcfr: 
Creating Folder from girder-bug
Uploading Item from file_10
Uploading Item from file_11
Uploading Item from file_12
Uploading Item from file_13
Uploading Item from file_14
Uploading Item from file_15
Uploading Item from file_16
Uploading Item from file_17
Uploading Item from file_18
Uploading Item from file_19
Uploading Item from file_20
Uploading Item from file_21
Uploading Item from file_22
Uploading Item from file_23
Uploading Item from file_24
Uploading Item from file_25
Uploading Item from file_26
Uploading Item from file_27
Uploading Item from file_28
Uploading Item from file_29
Uploading Item from file_30
Uploading Item from file_31
Uploading Item from file_32
Uploading Item from file_33
Traceback (most recent call last):
  File "/home/jcfr/.virtualenvs/girder/bin/girder-cli", line 9, in <module>
    load_entry_point('girder-client==1.0.0', 'console_scripts', 'girder-cli')()
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/cli.py", line 96, in main
    reuse_existing=args.reuse)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 895, in upload
    leaf_folders_as_items, reuse_existing)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 852, in _upload_folder_recursive
    entry, folder['_id'], full_entry, reuse_existing)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 758, in _upload_as_item
    local_file, current_item['_id'], file_path)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 741, in _upload_file_to_item
    self.uploadFileToItem(parent_item_id, file_path)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 470, in uploadFileToItem
    obj = self.post(path, parameters=parameters, files=filedata)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 220, in post
    return self.sendRestRequest('POST', path, parameters, files=files)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 214, in sendRestRequest
    text=result.text)
girder_client.HttpError: HTTP error 500: POST http://<hostname>:80/api/v1/file/chunk?uploadId=55c91d8d56d1f3474322d9a3&offset=0
```

**Comment by zachmullen** [comment]
We should see that one in the error log for the server

**Comment by jcfr** [comment]
> We should see that one in the error log for the server

Content of `/var/log/girder/error.log`:

```
[2015-08-10 21:55:44,913] ERROR: 500 Error
Traceback (most recent call last):
  File "/opt/radiomics/girder/girder/api/rest.py", line 295, in endpointDecorator
    val = fun(self, args, kwargs)
  File "/opt/radiomics/girder/girder/api/rest.py", line 794, in POST
    return self.handleRoute(method, path, params)
  File "/opt/radiomics/girder/girder/api/rest.py", line 582, in handleRoute
    val = handler(**kwargs)
  File "/opt/radiomics/girder/girder/api/access.py", line 50, in accessDecorator
    return fun(*args, **kwargs)
  File "/opt/radiomics/girder/girder/api/v1/file.py", line 185, in readChunk
    return self.model('upload').handleChunk(upload, chunk.file)
  File "/opt/radiomics/girder/girder/models/upload.py", line 60, in handleChunk
    upload = self.save(adapter.uploadChunk(upload, chunk))
  File "/opt/radiomics/girder/girder/utility/s3_assetstore_adapter.py", line 180, in uploadChunk
    return self._proxiedUploadChunk(upload, chunk)
  File "/opt/radiomics/girder/girder/utility/s3_assetstore_adapter.py", line 240, in _proxiedUploadChunk
    headers=self._getRequestHeaders(upload))
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
error: [Errno 104] Connection reset by peer
Additional info:
  Request URL: POST http://<hostname>/api/v1/file/chunk
  Query string: uploadId=55c91d8d56d1f3474322d9a3&offset=0
  Remote IP: 127.0.0.1
```

**Comment by jcfr** [comment]
It turns out that there are files > 32MB that I would like to upload to girder using the client. @zachmullen @mgrauer Do you think it is an issue with boto ? do you know what should be updated in `girder_client` to make use of https://github.com/boto/boto/issues/2207#issuecomment-60682869c ?

**Comment by mgrauer** [comment]
@jcfr This is actually an issue of boto on the server side, although we use boto in the girder-client and in the S3 assetstore adapter.

Would you be able to try the following and report back?

Change the [MAX_CHUNK_SIZE](https://github.com/girder/girder/blob/master/clients/python/girder_client/__init__.py#L97) in your local girder-client from `1024*1024*64` to `1024*1024*32` and try the upload again.

**Comment by jcfr** [comment]
@mgrauer Just tried and got similar error. Thanks for your help with this.

* girder_client:

```
Traceback (most recent call last):
  File "/home/jcfr/.virtualenvs/girder/bin/girder-cli", line 9, in <module>
    load_entry_point('girder-client==1.0.0', 'console_scripts', 'girder-cli')()
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/cli.py", line 96, in main
    reuse_existing=args.reuse)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 895, in upload
    leaf_folders_as_items, reuse_existing)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 852, in _upload_folder_recursive
    entry, folder['_id'], full_entry, reuse_existing)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 758, in _upload_as_item
    local_file, current_item['_id'], file_path)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 741, in _upload_file_to_item
    self.uploadFileToItem(parent_item_id, file_path)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 470, in uploadFileToItem
    obj = self.post(path, parameters=parameters, files=filedata)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 220, in post
    return self.sendRestRequest('POST', path, parameters, files=files)
  File "/home/jcfr/.virtualenvs/girder/local/lib/python2.7/site-packages/girder_client/__init__.py", line 214, in sendRestRequest
    text=result.text)
girder_client.HttpError: HTTP error 500: POST http://<hostname>:80/api/v1/file/chunk?uploadId=55ca138756d1f34aeb4a1fe5&offset=0
```

* server side - `/var/log/girder/error.log`:

```
Traceback (most recent call last):
  File "girder/api/rest.py", line 295, in endpointDecorator
    val = fun(self, args, kwargs)
  File "girder/api/rest.py", line 794, in POST
    return self.handleRoute(method, path, params)
  File "girder/api/rest.py", line 582, in handleRoute
    val = handler(**kwargs)
  File "girder/api/access.py", line 50, in accessDecorator
    return fun(*args, **kwargs)
  File "girder/api/v1/file.py", line 185, in readChunk
    return self.model('upload').handleChunk(upload, chunk.file)
  File "girder/models/upload.py", line 60, in handleChunk
    upload = self.save(adapter.uploadChunk(upload, chunk))
  File "girder/utility/s3_assetstore_adapter.py", line 180, in uploadChunk
    return self._proxiedUploadChunk(upload, chunk)
  File "girder/utility/s3_assetstore_adapter.py", line 240, in _proxiedUploadChunk
    headers=self._getRequestHeaders(upload))
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
error: [Errno 104] Connection reset by peer
Additional info:
  Request URL: POST http://<hostname>/api/v1/file/chunk
  Query string: uploadId=55ca138756d1f34aeb4a1fe5&offset=0
  Remote IP: 127.0.0.1
```

**Comment by mgrauer** [comment]
@zachmullen 

If I use the girder-client => girder => S3 upload path, with a large file (~93MB), and I **do not** pass the headers for the [`upload_part_from_file` call](https://github.com/girder/girder/blob/master/girder/utility/s3_assetstore_adapter.py#L238-L240), then the proxied upload suceeds.  This works regardless of the girder-client chunk size, 16M, 32M, or 64M.  

An example of these headers is 

```{'x-amz-meta-authorized-length': '96665353', 'x-amz-acl': 'private', 'Content-Disposition': 'attachment; filename="girder-plugins-1.3.1.tar.gz"', 'x-amz-meta-uploader-id': '55ca2e4e56d1f34aeb4a1fe7', 'x-amz-meta-uploader-ip': '127.0.0.1', 'Content-Type': u'application/octet-stream'}```.

Possibly some interaction of our headers with boto's headers?  There seem to be known issues in boto related to the [100 continue header](https://github.com/boto/boto/issues/2207).

I can also upload directly from a filesystem to S3 using [boto multipart upload](http://boto.readthedocs.org/en/latest/s3_tut.html#storing-large-data), on a large file, without setting any headers.


Another weird case I found is that uploading a file exactly 32M (`1024*1024*32`) with a 16M chunk size on the girder-client fails.  32M and 64M chunk sizes on the girder-client succeed.  In all of these cases with the 32M file, girder uses the [`set_contents_from_file call`](https://github.com/girder/girder/blob/master/girder/utility/s3_assetstore_adapter.py#L244-L245).

**Comment by zachmullen** [comment]
Did this get sorted out yet? I'm curious to see if #933 fixes this.

**Comment by mgrauer** [comment]
No change that I am aware of.  Perhaps @jcfr and I can try next week.

**Comment by zachmullen** [comment]
If #933 doesn't fix it for free, I'd like to try the suggestion of [this comment](https://github.com/boto/boto/issues/2207#issuecomment-60682869) in the thread you linked and see if that's the issue.

**Comment by mgrauer** [comment]
I had tried that suggestion (specifying region) earlier, but no luck.  I'll at least give it another try next week if #933 doesn't work.

**Comment by zachmullen** [comment]
I believe this has been fixed, if you still encounter this error please reopen.
